### ISSUE TITLE
demo-rawlog-velodyne-slam configuration/setting error

### ISSUE THREAD

**Issue by TankPi** [MOLAorg/mola#39]
I try to run the demo: [demo-rawlog-velodyne-slam](https://docs.mola-slam.org/latest/demo-rawlog-velodyne-slam.html), but I get the following error:

![Screenshot from 2021-03-22 12-15-29](https://user-images.githubusercontent.com/11289683/112002579-54a13f00-8b20-11eb-904b-6a65190ee956.png)

When I check the [rawlog_odom_and_lidar.yml](https://github.com/MOLAorg/mola/blob/master/demos/rawlog_odom_and_lidar.yml#L113):
```yaml
      # And its params:
      # Case: WITH a good twist (velocity) model:
      icp_params_with_vel.maxIterations:  10    90
      icp_params_with_vel.thresholdDist:   1.0   0.50   # [meters]
      icp_params_with_vel.thresholdAng:    2.0   0.01   # [deg]
      # Case: WITHOUT a good twist (velocity) model:
      icp_params_without_vel.maxIterations:   5     100
      icp_params_without_vel.thresholdDist:   3.0   0.50  # [meters]
      icp_params_without_vel.thresholdAng:    2.0   0.01  # [deg]
      # Case: Loop closure
      loop_closure_montecarlo_samples: 10
      icp_params_loopclosure.maxIterations: 10    40    90
      icp_params_loopclosure.thresholdDist: 30.0  5.0  0.50  # [meters]
      icp_params_loopclosure.thresholdAng:   2.0  0.5  0.01  # [deg]
```

The parameter names  `icp_params_with_vel` seem incorrect (I assume should be `icp_settings_with_vel`). When I try to correct this I still get the error. Can you try help me correct the yaml-file? Thanks!

PS: demo `ros1_velodyne_slam` seems to have the same problem.
