### ISSUE TITLE
Empty /tf transforms published

### ISSUE THREAD

**Issue by scrouthtv** [MOLAorg/mola#76]
Hi, I'm having a problem where MOLA is publishing empty /tf transforms:
```
transforms:
- header:
    stamp:
      sec: 1738245906
      nanosec: 581764936
    frame_id: ''
  child_frame_id: ''
  transform:
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
```
This results in another error in the mola pipeline:
```
[mola-cli-1] Error:   TF_SELF_TRANSFORM: Ignoring transform from authority "Authority undetectable" with frame_id and  child_frame_id "" because they are the same
[mola-cli-1]          at line 211 in ./src/buffer_core.cpp
[mola-cli-1] Error:   TF_NO_CHILD_FRAME_ID: Ignoring transform from authority "Authority undetectable" because child_frame_id not set 
[mola-cli-1]          at line 219 in ./src/buffer_core.cpp
[mola-cli-1] Error:   TF_NO_FRAME_ID: Ignoring transform with child_frame_id ""  from authority "Authority undetectable" because frame_id not set
[mola-cli-1]          at line 226 in ./src/buffer_core.cpp
```
I am using the default configuration like: `ros2 launch mola_lidar_odometry ros2-lidar-odometry.launch.py`
Does anyone else have this error?
